
language: php

env:
    - RUN=phpunit
    - RUN=vendor/bin/phpunit
    - RUN=vendor/bin/phing

script: ${RUN}

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - "composer selfupdate"
    - "composer --version"
    - "composer install --prefer-dist --verbose"
