---
    php_ppa: php5
    doc_root: /vagrant
    sys_packages: []
    timezone: America/Sao_Paulo
    dist: precise
    php_packages: ["php5-cli","php5-ldap","php5-odbc","php5-sybase","php5-sqlite","php5-xsl","php5-xdebug"]
